service: reminder

package:
  individually: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    ACCOUNT: '166257563783'
    DYNAMODB_TABLE: ${self:service}
    AWS_UTILS: 22

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  get_reminder:
    handler: reminder/dynamodb/get_reminder.get_reminder
    events:
      - http:
          path: reminder/{id}
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  put_reminder:
    handler: reminder/dynamodb/put_reminder.put_reminder
    events:
      - http:
          path: reminder
          method: post
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  scan_reminders:
    handler: reminder/dynamodb/scan_reminders.scan_reminders
    events:
      - http:
          path: reminder
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  filter_scan_reminders:
    handler: reminder/dynamodb/filter_scan_reminders.filter_scan_reminders
    events:
      - http:
          path: reminder/filter
          method: post
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  get_today_reminders:
    handler: reminder/dynamodb/get_today_reminders.get_today_reminders
    events:
      - http:
          path: reminder/today
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"