service: reminder-backend

package:
  individually: true

plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    REMINDER_TABLE: 'reminder'

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.REMINDER_TABLE}"

functions:
  get:
    handler: reminder/dynamodb/get.get
    events:
      - http:
          path: dynamodb/{id}
          method: get
          cors: true
  create:
    handler: reminder/dynamodb/create.create
    events:
      - http:
          path: dynamodb
          method: post
          cors: true