service: reminder

package:
  individually: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    ACCOUNT: '166257563783'
    DYNAMODB_TABLE: ${self:service}
    AWS_UTILS: "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:11"

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  get:
    handler: reminder/dynamodb/get_reminder.get_reminder
    events:
      - http:
          path: dynamodb/{id}
          method: get
          cors: true
    layers:
      - ${self:provider.environment.AWS_UTILS}
  create:
    handler: reminder/dynamodb/create_reminder.create_reminder
    events:
      - http:
          path: dynamodb
          method: post
          cors: true
    layers:
      - ${self:provider.environment.AWS_UTILS}
  scan:
    handler: reminder/dynamodb/get_all_reminders.get_all_reminders
    events:
      - http:
          path: dynamodb
          method: get
          cors: true
    layers:
      - ${self:provider.environment.AWS_UTILS}