service: reminder

package:
  individually: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    ACCOUNT: '166257563783'
    DYNAMODB_TABLE: ${self:service}
    AWS_UTILS: 15

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  get_reminder:
    handler: reminder/dynamodb/get_reminder.get_reminder
    events:
      - http:
          path: reminders/{id}
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  create_reminder:
    handler: reminder/dynamodb/create_reminder.create_reminder
    events:
      - http:
          path: reminders
          method: post
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  get_all_reminders:
    handler: reminder/dynamodb/get_all_reminders.get_all_reminders
    events:
      - http:
          path: reminders
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  get_filter_reminders:
    handler: reminder/dynamodb/get_filter_reminders.get_filter_reminders
    events:
      - http:
          path: reminders/filter
          method: post
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"
  get_today_reminders:
    handler: reminder/dynamodb/get_today_reminders.get_today_reminders
    events:
      - http:
          path: reminders/today
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"