service: reminder

package:
  individually: true

plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    DYNAMODB_TABLE: ${self:service}

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  get:
    handler: reminder/dynamodb/get.get
    events:
      - http:
          path: dynamodb/{id}
          method: get
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:*:layer:aws-utils:8"
  create:
    handler: reminder/dynamodb/create_reminder.create_reminder
    events:
      - http:
          path: dynamodb
          method: post
          cors: true
    layers:
      - "arn:aws:lambda:${opt:region, self:provider.region}:*:layer:aws-utils:8"
